import 'package:get/get.dart';

class MyTransaction extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "ar": {
          "ar": "العربية",
          "en": "الأنجليزية",
          "bottom1": "متابعة",
          "bottom2": "تخطي",
          "page1_title": "أختر المنتج",
          "page1_description": "لدينا 100,000 منتج واختر\n منتجك من متجرنا",
          "page2_title": "سهل و أمن للشراء",
          "page2_description":
              "يمكنك الدفع نقدا أو من خلال\n بوابات الدفع الإلكتروني",
          "page3_title": "تتبع طلبك",
          "page3_description":
              "يمكنك تتبع طلبك في كل مرحلة\n وتتبعه أيضا من خلال الخريطة",
          "sign_in": "تسجيل الدخول",
          "welcome_back": "مرحبا بعودتك",
          "sign_des":
              "يمكنك تسجيل الدخول من خلال \nالبريد وكلمة السر او خلال رسائل \nالتواصل الاجتماعي",
          "email": "البريد الألكتروني",
          "password": "كلمة المرور",
          "enter_your_email": "أدخل بريدك الألكتروني",
          "enter_your_password": "أدخل كلمة المرور",
          "re_enter_your_password": "اعد كتابة كلمة المرور",
          "forget_password": "هل نسيت كلمة المرور؟",
          "signin_button": "تسجيل الدخول",
          "don't_have_an_account": "ليس لديك حساب ؟",
          "sign_up_des": "أنشئ حساب",
          "sign_up": "إنشاء حساب جديد",
          "user_name": "أدخل اسم المستخدم",
          "name": "الأسم",
          "phone": "رقم الهاتف",
          "enter_your_phone": "أدخل رقم الهاتف",
          "signup_button": "أنشئ حساب جديد",
          "have_an_account": "هل لديك حساب بالفعل ؟",
          "sign_in_des": "تسجيل الدخول",
          "signup_des": "الرجاء إدخال عنوان بريدك\nالإلكتروني لتلقي رمز التحقق",
          "reset_password": "هل نسيت كلمة المرور",
          "check_email": "تحقق البريد الإلكتروني",
          "check": "تحقق",
          "VerificationCode": "رمز التحقق",
          "check_code": "التحقق من الرمز",
          "verifiy_des": "الرجاء ادخال رمز التحقق المرسل إليك",
          "Save": "حفظ",
          "reset_des": "الرجاء إدخال كلمة المرور الجديدة",
          "newpass": "كلمة المرور الجديده",
          "resetpassword": "أعاده تعيين كلمة المرور",
          "Check_Email": "تحقق من البريد الألكتروني",
          "Congratulations": "تهانينا",
          "Success_des": "تم التحقق من البريد",
          "goToLogin": "اذهب إلى تسجيل الدخول",
          "Alert": "تنبية",
          "Do_you_want_to_close_the_application": "هل تريد إغلاق التطبيق؟",
          "Cancel": "إلغاء",
          "Confirm": "متابعة",
          "find_product": "ابحث عن المنتج",
          "Camera": "كاميرا",
          "Computer": "كمبيوتر",
          "Dress": "فستان",
          "Shoes": "أحذية",
          "Phone": "هاتف",
          "ASummerSurprise": "مفاجأة الصيف",
          "Cashback20%": "استرداد نقدي 20%",
          "ProductForYou": "المنتج المناسب لك",
          "Offers": "عروض",
          "Categories": "الأقسام",
          "Home": "الرئيسية",
          "Settings": "الأعدادات",
          "Favorite": "المفضلة",
          "Profile": "حسابي",
          "Notifications": "الاشعارات",
          "DisableNotifications": "إغلاق الأشعارات",
          "Address": "العنوان",
          "Aboutus": "من نحن",
          "Contactus": "أتصل بنا",
          "Logout": "تسجيل الخروج",
          "Color": "اللون",
          "Red": "أحمر",
          "Black": "أسود",
          "Green": "أخضر",
          "GoToCart": "الذهاب الي السلة",
          "E-Mail": "البريد الألكتروني",
          "PhoneNumber": "رقم الهاتف",
          "About": "تفاصيل",
          "Location": "الموقع",
          "Shipping": "الشحن",
          "TotalPrice": "إجمالي السعر",
          "Price": "السعر",
          "PlaceOrder": "أطلب الاوردر",
          "MyCart": "السلة",
          "YouHave2IteminYourList": "انت لديك 2 منتج في السله الخاصة بك",
          "Trend Market": "تريند ماركت",
          "Description": "الوصف",
          "SelectColor": "تحديد اللون",
          "TheProductHasBeenRemovedFromFavorites": "تم حذف المنتج من المفضلة",
          "TheProductHasBeenAddedToFavorites": "تم اضافة المنتج الي المفضلة",
          "resend": "أعادة ارسال",
          "MyFavorite": "المفضلة",
          "TheProductHasBeenAddedToCart": "تم اضافة المنتج إلي السلة",
          "TheProductHasBeenRemovedFromCart": "تم حذف المنتج من السلة",
          "MyAddress": "العناوين",
          "AddNewAddress": "أضافة عنوان جديد",
          "city": "المدينة",
          "street": "الشارع",
          "namelocation": "العنوان كامل",
          "Add": "أضافة",
          "apply": "تطبيق",
          "couponCode": "كود الخصم",
          "discount": "الخصم",
          "CouponCode:": "كود الخصم:",
          "YouHave": "لديك",
          "IteminYourList": "العناصر الموجودة في قائمتك",
          "CheckOut": "الدفع",
          "ChoosePaymentMethod": "اختر طريقة الدفع",
          "Cash": "الدفع عند الاستلام",
          "PaymentCards": "بطاقات الدفع",
          "ChooseDeliveryType": "اختر نوع التسليم",
          "Delivery": "توصيل",
          "receive": "استلام",
          "ShippingAddress": "عنوان الشحن",
          "Cartempty": "السلة فارغه",
          "Orderedsuccessfully": "تم الطلب بنجاح",
          "PleaseselectaorderType": "الرجاء تحديد طلب نوع",
          "Pleaseselectapaymentmethod": "يرجى اختيار طريقة الدفع",
          "Rating3.5": "تقييم 3.5",
          "Success": "تم بنجاح",
          "tryagain": "حاول مرة اخري",
          "notvalidusername": "اسم مستخدم غير صالح",
          "notvalidphone": "رقم الهاتف غير صالح",
          "can'tbeEmpty": "لا يمكن أن تكون فارغة",
          "Warning": "تحذير",
          "Your address has been added": "تم أضافة عنوانك",
          "Rating 3.5": "تقييم 3.5",
          "notvalidemail": "البريد إلكتروني غير صالح",
          "PasswordOrEmailAlreadyExists":
              "كلمة المرور أو البريد الإلكتروني موجودة بالفعل",
          "PhoneNumberOrEmailAlreadyExists":
              "رقم الهاتف أو البريد الإلكتروني موجود بالفعل",
          "VerifyCodeNotCorrect": "تحقق من الرمز غير صحيح",
          "massegeAbout":
              "نحن تطبيق تجارة الكترونية نبيع كثير من انواع المنتجات , نسهل علي العميل عملية الشراء و البحث عن المنتج بشكل بسيط و سهل .",
        },
        "en": {
          "ar": "Arabic",
          "en": "English",
          "bottom1": "Continue",
          "bottom2": "skip",
          "page1_title": "Choose Product",
          "page1_description":
              "We Have 100,000 Products \n And Choose Your Product \n From Our Store",
          "page2_title": "Easy And Safe To Buy",
          "page2_description":
              "You Can Pay in Cash or \n Through Electronic \n Payment Gateways",
          "page3_title": "Track Your Order",
          "page3_description":
              "You Can Track Your Order At \n Every Stage And Also Track \n It Through The Map",
          "sign_in": "Sign In",
          "welcome_back": "Welcome Back",
          "sign_des":
              "You can login using your\nemail and password or\nthrough social media messages",
          "email": "Email",
          "password": "Password",
          "enter_your_email": "Email",
          "re_enter_your_password": "Confirm Password",
          "forget_password": "Forget Password?",
          "signin_button": "Sign In",
          "don't_have_an_account": "Don't have an Account ?",
          "sign_up_des": "Sign Up",
          "sign_up": "Sign Up",
          "user_name": "Username",
          "name": "Name",
          "enter_your_phone": "Mobile Number",
          "phone": "Phone",
          "signup_button": "SignUp",
          "have_an_account": "Have An Account ?",
          "sign_in_des": "Sign In",
          "signup_des":
              "Please Enter Your Email Address To Receive A Verification Code",
          "reset_password": "Forget Password",
          "check_email": "Check Email",
          "check": "Check",
          "check_code": "Check Code",
          "VerificationCode": "Verification Code",
          "verifiy_des": "Please Enter The Digit Code Sent To",
          "Save": "Save",
          "reset_des": "Please Enter New Password",
          "newpass": "New Password",
          "resetpassword": "Reset Password",
          "Check_Email": "Check Email",
          "Success": "Success",
          "Congratulations": "Congratulations",
          "Success_des": "Email verified",
          "goToLogin": "Go To Login",
          "Alert": "Alert",
          "Do_you_want_to_close_the_application":
              "Do You Want To Close The Application",
          "Cancel": "Cancel",
          "Confirm": "Confirm",
          "find_product": "Find Product",
          "Camera": "Camera",
          "Computer": "Computer",
          "Dress": "Dress",
          "Shoes": "Shoes",
          "Phone": "Phone",
          "ASummerSurprise": "A Summer Surprise",
          "Cashback20%": "Cashback 20%",
          "ProductForYou": "Product For You",
          "Offers": "Offers",
          "Categories": "Categories",
          "Home": "Home",
          "Settings": "Settings",
          "Favorite": "Favorite",
          "Profile": "Profile",
          "Notifications": "Notifi",
          "DisableNotifications": "Disable Notifications",
          "Address": "Address",
          "Aboutus": "About us",
          "Contactus": "Contact us",
          "Logout": "Logout",
          "Color": "Color",
          "Red": "Red",
          "Black": "Black",
          "Green": "Green",
          "GoToCart": "Go To Cart",
          "E-Mail": "E-Mail",
          "PhoneNumber": "Phone Number",
          "About": "About",
          "Location": "Location",
          "Shipping": "Shipping",
          "TotalPrice": "Total Price",
          "Price": "Price",
          "PlaceOrder": "Place Order",
          "MyCart": "My Cart",
          "YouHave2IteminYourList": "You Have 2 Itemin Your List",
          "Trend Market": "Trend Market",
          "Description": "Description",
          "SelectColor": "Select Color",
          "TheProductHasBeenRemovedFromFavorites":
              "The Product Has Been Removed From Favorites",
          "TheProductHasBeenAddedToFavorites":
              "The Product Has Been Added To Favorites",
          "resend": "Resend",
          "MyFavorite": "My Favorite",
          "TheProductHasBeenAddedToCart": "The Product Has Been Added To Cart",
          "TheProductHasBeenRemovedFromCart":
              "The Product Has Been Removed From Cart",
          "MyAddress": "Address",
          "AddNewAddress": "Add New Address",
          "city": "City",
          "street": "Street",
          "namelocation": "Name Location",
          "Add": "Add",
          "apply": "Apply",
          "couponCode": "Coupon Code",
          "discount": "Discount",
          "CouponCode:": "Coupon Code:",
          "YouHave": "You Have",
          "IteminYourList": "Items in Your List",
          "CheckOut": "Check Out",
          "ChoosePaymentMethod": "Choose Payment Method",
          "Cash": "Cash On Delivery",
          "PaymentCards": "Payment Cards",
          "ChooseDeliveryType": "Choose Delivery Type",
          "Delivery": "Delivery",
          "receive": "Receive",
          "ShippingAddress": "Shipping Address",
          "Cartempty": "Cart empty",
          "Orderedsuccessfully": "Ordered successfully",
          "PleaseselectaorderType": "Please Select A Order Type",
          "Pleaseselectapaymentmethod": "Please Select A Payment Method",
          "Rating3.5": "Rating 3.5",
          "tryagain": "Try Again",
          "Warning": "Warning",
          "PasswordOrEmailAlreadyExists": "Password Or Email Already Exists",
          "VerifyCodeNotCorrect": "Verify Code Not Correct",
          "PhoneNumberOrEmailAlreadyExists":
              "Phone Number Or Email Already Exists",
          "massegeAbout":
              "We apply electronic commerce we sell many kinds of products, we make it easier for the customer to purchase and search for the product simple and easy.",
          "notvalidusername": "not valid username",
          "notvalidemail": "not valid email",
          "notvalidphone": "not valid phone number",
          "can'tbeEmpty": "can't be Empty",
          "Rating 3.5": "Rating 3.5",
          "Your address has been added": "Your address has been added",
        }
      };
}
